[package]
authors = ["Alexandre Bury <alexandre.bury@gmail.com>"]
categories = ["command-line-interface", "gui"]
description = "A TUI (Text User Interface) library focused on ease-of-use."
documentation = "https://docs.rs/cursive"
keywords = ["ncurses", "TUI", "UI"]
license = "MIT"
name = "cursive"
readme = "../Readme.md"
repository = "https://github.com/gyscos/cursive"
version = "0.16.3"
edition = "2018"

[package.metadata.docs.rs]
features = ["unstable_scroll", "markdown", "toml"]

[dependencies]
cursive_core = { path = "../cursive-core", version= "0.2.2"}
crossbeam-channel = "0.5"
cfg-if = "1"
enumset = "1.0.3"
unicode-segmentation = "1"
unicode-width = "0.1"
lazy_static = "1"
libc = "0.2"
term_size = { version = "0.3", optional = true }
maplit = { version = "1.0", optional = true }
log = "0.4"
ahash = "0.6"

[dependencies.bear-lib-terminal]
optional = true
version = "2"

[dependencies.ncurses]
features = ["wide"]
optional = true
version = "5.99.0"

[dependencies.pancurses]
features = ["wide"]
optional = true
version = "0.16"

[dependencies.termion]
optional = true
version = "1"

[dependencies.crossterm]
optional = true
version = "0.19"

[features]
blt-backend = ["bear-lib-terminal"]
default = ["ncurses-backend"]
ncurses-backend = ["ncurses", "maplit", "term_size"]
pancurses-backend = ["pancurses", "maplit", "term_size"]
termion-backend = ["termion"]
crossterm-backend = ["crossterm"]
markdown = ["cursive_core/markdown"]
unstable_scroll = ["cursive_core/unstable_scroll"]
toml = ["cursive_core/toml"]

[lib]
name = "cursive"

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3"
